//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cordial.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_gb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_gb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cordial.Resources.Languages.en-gb", typeof(en_gb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string edit_selectall {
            get {
                return ResourceManager.GetString("edit_selectall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        internal static string file_close {
            get {
                return ResourceManager.GetString("file_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to Notification Tray.
        /// </summary>
        internal static string file_closetotray {
            get {
                return ResourceManager.GetString("file_closetotray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export feeds as ompl.
        /// </summary>
        internal static string file_exportopml {
            get {
                return ResourceManager.GetString("file_exportopml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import feeds from opml....
        /// </summary>
        internal static string file_importopml {
            get {
                return ResourceManager.GetString("file_importopml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences....
        /// </summary>
        internal static string file_preferences {
            get {
                return ResourceManager.GetString("file_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string file_quit {
            get {
                return ResourceManager.GetString("file_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        internal static string file_showwindow {
            get {
                return ResourceManager.GetString("file_showwindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup.
        /// </summary>
        internal static string generic_cleanup {
            get {
                return ResourceManager.GetString("generic_cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string generic_download {
            get {
                return ResourceManager.GetString("generic_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string generic_downloads {
            get {
                return ResourceManager.GetString("generic_downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download speed: {0}kB/s.
        /// </summary>
        internal static string generic_downloadspeed {
            get {
                return ResourceManager.GetString("generic_downloadspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string generic_edit {
            get {
                return ResourceManager.GetString("generic_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string generic_file {
            get {
                return ResourceManager.GetString("generic_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string generic_help {
            get {
                return ResourceManager.GetString("generic_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Downloads: {0}.
        /// </summary>
        internal static string generic_livedownloads {
            get {
                return ResourceManager.GetString("generic_livedownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string generic_log {
            get {
                return ResourceManager.GetString("generic_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string generic_no {
            get {
                return ResourceManager.GetString("generic_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Check.
        /// </summary>
        internal static string generic_runcheck {
            get {
                return ResourceManager.GetString("generic_runcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string generic_subscribe {
            get {
                return ResourceManager.GetString("generic_subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        internal static string generic_subscriptions {
            get {
                return ResourceManager.GetString("generic_subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string generic_tools {
            get {
                return ResourceManager.GetString("generic_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string generic_view {
            get {
                return ResourceManager.GetString("generic_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string generic_yes {
            get {
                return ResourceManager.GetString("generic_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string help_about {
            get {
                return ResourceManager.GetString("help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        internal static string help_checkupdates {
            get {
                return ResourceManager.GetString("help_checkupdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        internal static string help_reportproblem {
            get {
                return ResourceManager.GetString("help_reportproblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Great Britain).
        /// </summary>
        internal static string human_name {
            get {
                return ResourceManager.GetString("human_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feed.
        /// </summary>
        internal static string tools_addfeed {
            get {
                return ResourceManager.GetString("tools_addfeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch-up.
        /// </summary>
        internal static string tools_catchup {
            get {
                return ResourceManager.GetString("tools_catchup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        internal static string tools_checkall {
            get {
                return ResourceManager.GetString("tools_checkall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Selected.
        /// </summary>
        internal static string tools_checkselected {
            get {
                return ResourceManager.GetString("tools_checkselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Properties.
        /// </summary>
        internal static string tools_feedprops {
            get {
                return ResourceManager.GetString("tools_feedprops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Feed.
        /// </summary>
        internal static string tools_removefeed {
            get {
                return ResourceManager.GetString("tools_removefeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        internal static string tools_scheduler {
            get {
                return ResourceManager.GetString("tools_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string tools_selectlang {
            get {
                return ResourceManager.GetString("tools_selectlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available.
        /// </summary>
        internal static string update_caption {
            get {
                return ResourceManager.GetString("update_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a new version available, do you wish to update?.
        /// </summary>
        internal static string update_maintext {
            get {
                return ResourceManager.GetString("update_maintext", resourceCulture);
            }
        }
    }
}
