//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cordial.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class nl_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal nl_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cordial.Resources.Languages.nl-nl", typeof(nl_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer alles.
        /// </summary>
        internal static string edit_selectall {
            get {
                return ResourceManager.GetString("edit_selectall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venster sluiten.
        /// </summary>
        internal static string file_close {
            get {
                return ResourceManager.GetString("file_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluit naar systeemvak.
        /// </summary>
        internal static string file_closetotray {
            get {
                return ResourceManager.GetString("file_closetotray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporteer feeds naar OPML.
        /// </summary>
        internal static string file_exportopml {
            get {
                return ResourceManager.GetString("file_exportopml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importeer feeds uit OPML.
        /// </summary>
        internal static string file_importopml {
            get {
                return ResourceManager.GetString("file_importopml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorkeuren.
        /// </summary>
        internal static string file_preferences {
            get {
                return ResourceManager.GetString("file_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsluiten.
        /// </summary>
        internal static string file_quit {
            get {
                return ResourceManager.GetString("file_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon venster.
        /// </summary>
        internal static string file_showwindow {
            get {
                return ResourceManager.GetString("file_showwindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schoonmaken.
        /// </summary>
        internal static string generic_cleanup {
            get {
                return ResourceManager.GetString("generic_cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaden.
        /// </summary>
        internal static string generic_download {
            get {
                return ResourceManager.GetString("generic_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download snelheid: {0}kB/s.
        /// </summary>
        internal static string generic_downloadspeed {
            get {
                return ResourceManager.GetString("generic_downloadspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewerken.
        /// </summary>
        internal static string generic_edit {
            get {
                return ResourceManager.GetString("generic_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand.
        /// </summary>
        internal static string generic_file {
            get {
                return ResourceManager.GetString("generic_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string generic_help {
            get {
                return ResourceManager.GetString("generic_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Downloads: {0}.
        /// </summary>
        internal static string generic_livedownloads {
            get {
                return ResourceManager.GetString("generic_livedownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logboek.
        /// </summary>
        internal static string generic_log {
            get {
                return ResourceManager.GetString("generic_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        internal static string generic_no {
            get {
                return ResourceManager.GetString("generic_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer Check uit.
        /// </summary>
        internal static string generic_runcheck {
            get {
                return ResourceManager.GetString("generic_runcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonneren.
        /// </summary>
        internal static string generic_subscribe {
            get {
                return ResourceManager.GetString("generic_subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonnementen.
        /// </summary>
        internal static string generic_subscriptions {
            get {
                return ResourceManager.GetString("generic_subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gereedschap.
        /// </summary>
        internal static string generic_tools {
            get {
                return ResourceManager.GetString("generic_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beeld.
        /// </summary>
        internal static string generic_view {
            get {
                return ResourceManager.GetString("generic_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string generic_yes {
            get {
                return ResourceManager.GetString("generic_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over {0}.
        /// </summary>
        internal static string help_about {
            get {
                return ResourceManager.GetString("help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controleer op updates.
        /// </summary>
        internal static string help_checkupdates {
            get {
                return ResourceManager.GetString("help_checkupdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meld een probleem.
        /// </summary>
        internal static string help_reportproblem {
            get {
                return ResourceManager.GetString("help_reportproblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch (Nederlands).
        /// </summary>
        internal static string human_name {
            get {
                return ResourceManager.GetString("human_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed toevoegen.
        /// </summary>
        internal static string tools_addfeed {
            get {
                return ResourceManager.GetString("tools_addfeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binnenhalen.
        /// </summary>
        internal static string tools_catchup {
            get {
                return ResourceManager.GetString("tools_catchup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controleer alles.
        /// </summary>
        internal static string tools_checkall {
            get {
                return ResourceManager.GetString("tools_checkall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectievakje geselecteerd.
        /// </summary>
        internal static string tools_checkselected {
            get {
                return ResourceManager.GetString("tools_checkselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed eigenschappen.
        /// </summary>
        internal static string tools_feedprops {
            get {
                return ResourceManager.GetString("tools_feedprops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed verwijderen.
        /// </summary>
        internal static string tools_removefeed {
            get {
                return ResourceManager.GetString("tools_removefeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooster.
        /// </summary>
        internal static string tools_scheduler {
            get {
                return ResourceManager.GetString("tools_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer taal.
        /// </summary>
        internal static string tools_selectlang {
            get {
                return ResourceManager.GetString("tools_selectlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een update beschikbaar..
        /// </summary>
        internal static string update_caption {
            get {
                return ResourceManager.GetString("update_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een nieuwe versie beschikbaar, wilt u updaten?.
        /// </summary>
        internal static string update_maintext {
            get {
                return ResourceManager.GetString("update_maintext", resourceCulture);
            }
        }
    }
}
